export const vocabularyOptionsConfig = {
  "key1": 100,
  "key2": "testing",
  "key3": false,
  "yso": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": false,
    "prefLabel": false,
    "swedish": false,
    "english": false,
    "altLabels": false,
    "broaders": false,
    "narrowers": false,
    "associatives": false,
    "thematicGroup": false,
    "clarification": false,
    "reason": false,
    "toBeDescribedIn": false,
    "organization": false
  },
  "liiko": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": false,
    "prefLabel": false,
    "swedish": false,
    "english": false,
    "altLabels": false,
    "broaders": false,
    "narrowers": false,
    "associatives": false,
    "thematicGroup": false,
    "clarification": false,
    "reason": false,
    "toBeDescribedIn": false,
    "organization": false
  },
  "slm": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": false,
    "prefLabel": false,
    "swedish": false,
    "english": false,
    "altLabels": false,
    "broaders": false,
    "narrowers": false,
    "associatives": false,
    "thematicGroup": false,
    "clarification": false,
    "reason": false,
    "toBeDescribedIn": false,
    "organization": false
  },
  "juho": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": false,
    "prefLabel": false,
    "swedish": false,
    "english": false,
    "altLabels": false,
    "broaders": false,
    "narrowers": false,
    "associatives": false,
    "thematicGroup": false,
    "clarification": false,
    "reason": false,
    "toBeDescribedIn": false,
    "organization": false
  }
}