export const vocabularyOptionsConfig = {
  "key1": 100,
  "key2": "testing",
  "key3": true,
  "yso": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": true,
    "prefLabel": true,
    "swedish": true,
    "english": true,
    "altLabels": true,
    "broaders": true,
    "narrowers": true,
    "associatives": true,
    "thematicGroup": true,
    "clarification": true,
    "reason": true,
    "toBeDescribedIn": true,
    "organization": true
  },
  "liiko": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": true,
    "prefLabel": true,
    "swedish": true,
    "english": true,
    "altLabels": true,
    "broaders": true,
    "narrowers": true,
    "associatives": true,
    "thematicGroup": true,
    "clarification": true,
    "reason": true,
    "toBeDescribedIn": true,
    "organization": true
  },
  "slm": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": true,
    "prefLabel": true,
    "swedish": true,
    "english": true,
    "altLabels": true,
    "broaders": true,
    "narrowers": true,
    "associatives": true,
    "thematicGroup": true,
    "clarification": true,
    "reason": true,
    "toBeDescribedIn": true,
    "organization": true
  },
  "juho": {
    "alku": "yso on täällä",
    "CheckTermsAlsoInTheIncludedYSO": true,
    "type": true,
    "prefLabel": true,
    "swedish": true,
    "english": true,
    "altLabels": true,
    "broaders": true,
    "narrowers": true,
    "associatives": true,
    "thematicGroup": true,
    "clarification": true,
    "reason": true,
    "toBeDescribedIn": true,
    "organization": true
  }
}