#!/bin/bash
echo "Starting the building"
# npx rimraf ./dist && npx webpack --entry ./src/main.js  --mode production # orig
# To prevent ERR_OSSL_EVP_UNSUPPORTED error related to the older NODE version
export NODE_OPTIONS=--openssl-legacy-provider
npx webpack --entry ./src/main.js  --mode production
sleep 1
cp -p dist/components.js ../components.js
echo "components.js copied from dist folder to the root folder"
date +'%Y-%m-%d %H:%M'
