version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "hourly"
    branches:
      - "feature/sec-updates-and-grandes-babel-changes-plus-json5-issue-fixed"
      - "master"
