version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
  - package_manager: "npm"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "./component-bundler"
    update_schedule: "live"
    target_branch: "issue32-security-checks-20210818"
  - package_manager: "npm"
    directory: "./component-bundler"
    update_schedule: "live"
    target_branch: "issue32-security-checks-20210818"