name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker container
        run: ./start_container.sh

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install JavaScript dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
